version: '2'

services:
  app:
    image: correavitor4/python-aless-trab
    restart: always
    container_name: pweb-py
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "18000:8000"
